from typing import Dict, Any


def build_debug_report(summary: Dict[str, Any], error_summary: Dict[str, Any]) -> str:
    total = summary["total"]
    valid = summary["valid"]
    invalid = summary["invalid"]

    success_rate = round((valid / total) * 100, 2) if total else 0

    # --- system status ---
    if success_rate >= 95:
        status = "HEALTHY"
    elif success_rate >= 80:
        status = "DEGRADED"
    else:
        status = "FAILING"

    lines = []

    lines.append("===== PIPELINE DEBUG REPORT =====\n")

    # --- overview ---
    lines.append("📊 Dataset Overview")
    lines.append(f"- Total Rows: {total}")
    lines.append(f"- Valid Rows: {valid}")
    lines.append(f"- Invalid Rows: {invalid}")
    lines.append(f"- Success Rate: {success_rate}%\n")

    # --- error breakdown ---
    lines.append("⚠️ Error Breakdown\n")

    lines.append("By Type:")
    for k, v in error_summary["by_type"].items():
        lines.append(f"- {k}: {v}")
    lines.append("")

    lines.append("By Field:")
    for k, v in error_summary["by_field"].items():
        lines.append(f"- {k}: {v}")
    lines.append("")

    lines.append("By Stage:")
    for k, v in error_summary["by_stage"].items():
        lines.append(f"- {k}: {v}")
    lines.append("")

    # --- system status ---
    lines.append("🚨 System Status")
    lines.append(f"- {status}\n")

    lines.append("✔ Generated by Marketing Analytics Lab")

    return "\n".join(lines)